# Generated by Django 3.0.5 on 2020-04-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
